# Tweaked from https://github.com/StrikerRockers-Mods/VanillaTweaks/blob/1.15/.github/workflows/gradle.yml
name: Java CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Build
      run: chmod 777 gradlew
    - name: Build and Check
      run: ./gradlew check --stacktrace
    # - name: Launch Client
    #   run: ./gradlew runClient --stacktrace
    - name: Launch Server
      run: mkdir -p run/server && echo "eula=true" > run/server/eula.txt && ./gradlew runServer --stacktrace
